REST: delete user
vladimirshefer/ChessGrinder pull request #15
Opened 2024-02-22 14:05 UTC by sedub01

2024-02-22 14:18 UTC, vladimirshefer commented on src/main/resources/db/migration/V202402220000__alter_table__user_reputation_history_table__add_constraint.sql
> +ALTER TABLE user_reputation_history_table
Не связано с этой миграцией, но надо проверить что при удалении юзера, у связанных Participant ставится null, а не удаляется каскадом participant

2024-02-22 14:18 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +        if (!userId.equals(authenticatedUser.getId())) {
Давай разрешим еще админу удалять профили, но только если удаляемый пользователь не явзяется сам админом (админ не может удалить админа)

2024-02-22 14:18 UTC, vladimirshefer commented on frontend/src/pages/UserProfileEditPage/index.tsx
> +        const userConfirmation = prompt(loc("Are you sure?\nTo delete profile enter \n") + expectedConfirmation);
Я бы заставил пользователя ввести такой текст:
"Я подтверждаю удаление своего профиля " + name
Чтобы человеку пришлось полностью написать свое желание текстом

2024-02-22 14:20 UTC, vladimirshefer commented on frontend/src/pages/UserProfileEditPage/index.tsx
> +        const userConfirmation = prompt(loc("Are you sure?\nTo delete profile enter \n") + expectedConfirmation);
Надо добавить в сообщение "Deletion is final and can not be undone"

2024-02-22 14:22 UTC, sedub01 commented on src/main/resources/db/migration/V202402220000__alter_table__user_reputation_history_table__add_constraint.sql
> +ALTER TABLE user_reputation_history_table
Да

2024-02-25 13:34 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +        if (!userId.equals(authenticatedUser.getId())) {
Сделано

2024-02-25 14:04 UTC, sedub01 commented on frontend/src/pages/UserProfileEditPage/index.tsx
> +        const userConfirmation = prompt(loc("Are you sure?\nTo delete profile enter \n") + expectedConfirmation);
Да

2024-02-25 14:04 UTC, sedub01 commented on frontend/src/pages/UserProfileEditPage/index.tsx
> +        const userConfirmation = prompt(loc("Are you sure?\nTo delete profile enter \n") + expectedConfirmation);
Да

2024-02-25 14:33 UTC, vladimirshefer requested changes

2024-02-25 14:33 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/UserEntity.java
> +    public boolean isAdmin() {
Не, давай не делать тут никаких утильных методов.
Оно пока что в одном месте юзается

Todo: заинлайнить

2024-02-25 14:33 UTC, vladimirshefer commented on frontend/src/strings/locale_ru.ts
> +    "Enter \"": "Введите \"",
Вынести все спецсиволы вовне

2024-02-25 14:33 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +    private boolean isAllowedToBeDeleted(UUID userId, UserEntity authenticatedUser) {
Todo: заинлайнить метод

2024-02-25 14:59 UTC, sedub01 commented on frontend/src/strings/locale_ru.ts
> +    "Enter \"": "Введите \"",
Да

2024-02-25 14:59 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +    private boolean isAllowedToBeDeleted(UUID userId, UserEntity authenticatedUser) {
+

2024-02-25 15:38 UTC, vladimirshefer approved these changes

2024-02-25 17:34 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/entities/UserEntity.java
> +    public boolean isAdmin() {
+

2024-02-25 17:34 UTC, merged