REST: columns' auditing
vladimirshefer/ChessGrinder pull request #16
Opened 2024-03-24 09:46 UTC by sedub01

@vladimirshefer

2024-03-24 14:56 UTC, vladimirshefer requested changes

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/auditing/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<UUID> {
AuditorAware<String>

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/auditing/AuditorAwareImpl.java
> +        return Optional.ofNullable(((MyUserDetails) (authentication.getPrincipal())).getId());
это вообще работает?
я не уверен что там именно MyUserDetails.
А вообще тут проще всего брать .getPrincipal.getName - там хранится логин юзера

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/UserEntity.java
> +    private UUID createdBy;
String

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/UserEntity.java
> +    private UUID updatedBy;
String

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/security/MyUserDetails.java
> +    public UUID getId() {return userEntity.getId();}
delete

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_at TIMESTAMPTZ,
если у тебя OffsetDateTime, то разве там не должен быть просто timestamp? он же всегда UTC.
timestampTZ это жу с таймзоной, а у тебя в джаве OffsetDateTime - без таймзоны.

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_by UUID,
UUID -> VARCHAR

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +            ON DELETE SET NULL;
нене, тут никаких констрейнтов.
это просто строчки и ничего более.
удалить

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +UPDATE users_table SET created_by = id;
давай этого не будем делать, тусть будет NULL

2024-03-24 14:56 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_by UUID,
DEFAULT NULL? или оно и так по дефолту нулл?

2024-03-26 15:23 UTC, sedub01 commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +UPDATE users_table SET created_by = id;
А я против

2024-03-26 15:23 UTC, sedub01 commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_by UUID,
И так везде по дефолту будет нулл, типа колонка просто добавится и всё

2024-03-26 15:39 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/auditing/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<UUID> {
👌

2024-03-26 15:39 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/entities/UserEntity.java
> +    private UUID createdBy;
👌

2024-03-26 15:39 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/security/MyUserDetails.java
> +    public UUID getId() {return userEntity.getId();}
👌

2024-03-26 15:39 UTC, sedub01 commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_at TIMESTAMPTZ,
👌

2024-03-26 15:39 UTC, sedub01 commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +    ADD COLUMN updated_by UUID,
👌

2024-03-30 15:20 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/security/AuditorAwareImpl.java
> +        final var principal = (CustomOAuth2User) authentication.getPrincipal();
Перед кастом надо проверить 
```
if (!authentication.getPrincipal() instanceof CustomOauth2User) { return Optional.empty() }
```

2024-03-30 15:24 UTC, vladimirshefer requested changes

2024-03-30 15:24 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/BadgeEntity.java
> +    @Column(name = "created_at", nullable = false, updatable = false)
Они все nullable

2024-03-30 15:24 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/MatchEntity.java
> +    @Column(name = "created_at", nullable = false, updatable = false)
Они все nullable

2024-03-30 15:24 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/entities/MatchEntity.java
> +    @Column(name = "created_at", nullable = false, updatable = false)
Там даже в базе nullable

2024-03-30 15:25 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +UPDATE users_table SET created_by = id;
В джаве тоже nullable

2024-03-30 15:25 UTC, vladimirshefer commented on src/main/resources/db/migration/V202403130000__alter_tables__add_auditing_columns.sql
> +UPDATE users_table SET created_by = id;
Должно быть

2024-03-30 16:21 UTC, vladimirshefer approved these changes

2024-03-31 12:13 UTC, merged