REST: add tournament seaons
vladimirshefer/ChessGrinder pull request #18
Opened 2024-04-30 10:02 UTC by sedub01

@vladimirshefer

2024-04-30 10:25 UTC, AlBoldyrev commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            @RequestParam(required = false, name = "startSeasonDate") String startSeasonDateString,
startSeasonDateString - плохой нейминг, надо просто startSeasonDate

2024-04-30 10:27 UTC, AlBoldyrev commented on src/main/java/com/chessgrinder/chessgrinder/mappers/UserMapper.java
> +    public UserDto toDto(UserEntity user, Date startSeason, Date endSeason) {
Не, так не должно быть. Метод toDto должен просто переводить объект типа Entity в Dto, зависимости от начала и конца сезона быть не должно

2024-04-30 10:29 UTC, AlBoldyrev commented on src/main/java/com/chessgrinder/chessgrinder/mappers/UserMapper.java
> +    private BigDecimal calcSeasonPoints(UUID userId, Date startSeason, Date endSeason) {
Возвращать такой огромный return - это bad practice. 
Там ещё и стрим, поэтому при возникновении необходимости это дебажить - три раза пожалеешь о своём решении )

2024-04-30 10:33 UTC, AlBoldyrev requested changes

2024-04-30 14:43 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/utils/Pair.java
> +public class Pair <A, B>{
В джаве нет из коробки Pair.
Не надо использовать классы из JavaFX.
Советую использовать Map.Entry и AbstractMap.SimpleEntry.

2024-04-30 18:43 UTC, AlBoldyrev commented on src/main/java/com/chessgrinder/chessgrinder/utils/Pair.java
> +public class Pair <A, B>{
Если перейдешь по ссылке, то там написано

"A simple implementation of a Pair is available in the core Java libraries."

Ну можно конечно сказать, что javafx - это уже не из коробки, но я бы всё равно не создавал этот класс вручную

2024-04-30 21:24 UTC, vladimirshefer requested changes

2024-04-30 21:24 UTC, vladimirshefer commented on frontend/src/pages/UsersPage/index.tsx
> +    const startSeason = searchParams.get('startSeason');
`let [startSeason] = useSearchParam("startSeason", defaultValue)`

2024-04-30 21:24 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/utils/Pair.java
> +public class Pair <A, B>{
после прихода jigsaw не каждая джава имеет javafx из коробки
javafx классы не надо использовать

2024-04-30 21:24 UTC, vladimirshefer commented on frontend/src/pages/UsersPage/index.tsx
> +            }
не понял, а где возможность сделать запрос без дат сезона? чтобы он показывал по старинке для всего периода времени.
надо вернуть.
а еще в catch надо тоже делать `return null` после alert.

2024-05-01 09:57 UTC, sedub01 commented on frontend/src/pages/UsersPage/index.tsx
> +            }
И так показывается для всего периода времени, просто в таком случае даты сезона - null, т.е. отсутствуют

2024-05-03 17:52 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/mappers/UserMapper.java
> +    private BigDecimal calcSeasonPoints(UUID userId, Date startSeason, Date endSeason) {
Как по мне - нормально, я так и дебажил; в коде много где таких возвращаемых значений

2024-05-03 17:57 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/service/UserService.java
> +            throw new ResponseStatusException(400, "Can't parse start or end season date with format " + DATE_FORMAT_STRING, e);
Его можно подхватывать в catch, но его нельзя создавать, т.к. конструктор приватный + нет указания кода ошибки (будет просто 500)

2024-05-03 18:04 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/utils/Pair.java
> +public class Pair <A, B>{
Сделано

2024-05-03 18:05 UTC, sedub01 commented on frontend/src/pages/UsersPage/index.tsx
> +    const startSeason = searchParams.get('startSeason');
Нет никакого defaultValue - там просто будет NULL, отсутствие значения
useSearchParam не позволяет считывать все аргументы адресной строки, а мне нужны их количество

2024-05-04 11:45 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/mappers/UserMapper.java
> +    private BigDecimal calcSeasonPoints(UUID userId, Date startSeason, Date endSeason) {
Тем более IDE будет выдавать предупреждение, если так сделать

2024-05-04 12:22 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            @RequestParam(required = false, name = "startSeasonDate") String startSeasonDateString,
Нормальный

2024-05-06 14:42 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/service/UserService.java
> +            throw new ResponseStatusException(400, "Can't parse start or end season date with format " + DATE_FORMAT_STRING, e);
@AlBoldyrev это исключение показывает что сам формат невалидный. А не то что строка с датой не подходит по формату.
Плюс действительно у него нет публичных конструкторов.

@sedub01 а тебе просто для информации : можно с помощью ExceptionHandler в спринге настроить чтобы для конкретного исключения бросался не 500

2024-05-06 16:17 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            @RequestParam(required = false) String startSeasonDate,
TODO вернуть name = "startSeason"

2024-05-07 15:54 UTC, AlBoldyrev approved these changes

2024-05-07 17:17 UTC, vladimirshefer approved these changes

2024-05-07 17:19 UTC, merged