feat: add name's edit
vladimirshefer/ChessGrinder pull request #3
Opened 2024-01-20 16:45 UTC by sedub01

2024-01-22 18:49 UTC, UmarShabazov commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            throw new FullNameAlreadyTakenException(String.format("Full name \"%s\" already taken", newUserFullName));
FullNameAlreadyTakenException не может применяться в таком виде, так как существует высокая вероятность запрета для регистрации "тёзок", т.е. челов с одним ФИО.

2024-01-22 20:18 UTC, vladimirshefer requested changes

2024-01-23 18:42 UTC, vladimirshefer requested changes

2024-01-23 18:42 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            throw new ResponseStatusException(401, "Not logged in", null);
однострочный иф. добавить скобки

2024-01-23 18:42 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +        if (authUser == null) return;
однострочный иф. добавить скобки

2024-01-23 18:50 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            throw new FullNameAlreadyTakenException(String.format("Full name \"%s\" already taken", newUserFullName));
done

2024-01-23 18:50 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +            throw new ResponseStatusException(401, "Not logged in", null);
done

2024-01-23 18:51 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/controller/UserController.java
> +        if (authUser == null) return;
done

2024-01-23 18:55 UTC, vladimirshefer approved these changes

2024-01-23 19:41 UTC, merged