Feature/password login
vladimirshefer/ChessGrinder pull request #8
Opened 2024-01-29 14:14 UTC by vladimirshefer

2024-01-31 14:20 UTC, sedub01 requested changes

2024-01-31 14:20 UTC, sedub01 commented on frontend/src/lib/api/dto/index.ts
> +    email?: string
В той форме из приложения нет эмейла, только Имя пользователя

2024-01-31 14:20 UTC, sedub01 commented on frontend/src/lib/api/repository/LoginPageRepository.ts
> +        await restApiClient.post("/login", `username=${username}&password=${password}`) // toto urlencode parameters
Получается, логин и пароль передаются без защиты? Т.е. даже без csrf токена?

2024-01-31 14:20 UTC, sedub01 commented on frontend/src/pages/LoginPage/index.tsx
> +    let ENABLE_REGISTRATION_USERNAME_PASSWORD = mode === "local" || true
Значение будет истинным всегда

2024-01-31 14:20 UTC, sedub01 commented on frontend/src/pages/LoginPage/index.tsx
> +            alert("Incorrect username. Must start with letter and contain no special chars.")
Надо русифицировать (выше тоже)

2024-01-31 14:20 UTC, sedub01 commented on frontend/src/strings/locale_ru.ts
> +    "Can't update user's name": "Не удалось изменить имя пользователя",
Лишняя запятая

2024-01-31 14:20 UTC, sedub01 commented on src/main/java/com/chessgrinder/chessgrinder/dto/UserSignUpRequest.java
> +    private String email;
Нигде при входе не просится почта

2024-01-31 22:47 UTC, vladimirshefer commented on frontend/src/lib/api/dto/index.ts
> +    email?: string
deleted

2024-01-31 22:47 UTC, vladimirshefer commented on frontend/src/lib/api/repository/LoginPageRepository.ts
> +        await restApiClient.post("/login", `username=${username}&password=${password}`) // toto urlencode parameters
ну по идее они защищены просто ssl протоколом

2024-01-31 22:47 UTC, vladimirshefer commented on frontend/src/pages/LoginPage/index.tsx
> +    let ENABLE_REGISTRATION_USERNAME_PASSWORD = mode === "local" || true
заменил

2024-01-31 22:47 UTC, vladimirshefer commented on frontend/src/pages/LoginPage/index.tsx
> +            alert("Incorrect username. Must start with letter and contain no special chars.")
на эти месседжи пока что пофигу. главное кнопки на сайте чтобы были по русски

2024-01-31 22:48 UTC, vladimirshefer commented on frontend/src/strings/locale_ru.ts
> +    "Can't update user's name": "Не удалось изменить имя пользователя",
она не лишняя, так тоже правильно. js разрешает trailing comma

2024-01-31 22:48 UTC, vladimirshefer commented on src/main/java/com/chessgrinder/chessgrinder/dto/UserSignUpRequest.java
> +    private String email;
deleted

2024-02-02 15:00 UTC, sedub01 approved these changes

2024-02-02 16:37 UTC, merged